#!/usr/bin/env node
/**
 * Rabbit Hole build orchestrator.
 *
 *   node scripts/build.mjs                      production build → dist/
 *   node scripts/build.mjs --watch              development build, rebuilt on change
 *   node scripts/build.mjs --mode development   one-off development build
 *
 * Three pieces make up the extension:
 *   1. App build   — popup.html, options.html, background.js (ES modules)
 *   2. Content     — one self-contained IIFE per content script (they cannot be ES modules)
 *   3. Manifest    — generated by manifest.config.mjs
 */
import { mkdir, rm, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { build, loadEnv } from 'vite';
import { createManifest } from '../manifest.config.mjs';

const root = fileURLToPath(new URL('..', import.meta.url));
const dist = fileURLToPath(new URL('../dist', import.meta.url));

const argv = process.argv.slice(2);
const watch = argv.includes('--watch');
const modeIdx = argv.indexOf('--mode');
const mode = modeIdx >= 0 ? argv[modeIdx + 1] : watch ? 'development' : 'production';

const env = loadEnv(mode, root, 'VITE_');
const define = {
  __RH_DEV__: JSON.stringify(mode === 'development'),
  __RH_PREVIEW__: JSON.stringify(false),
};

const CONTENT_SCRIPTS = ['youtube', 'netflix', 'reddit', 'generic'];

async function main() {
  console.log(`▸ Rabbit Hole build (${mode}${watch ? ', watch' : ''})`);
  await rm(dist, { recursive: true, force: true });
  await mkdir(dist, { recursive: true });

  // 1 ─ app (popup, options, service worker)
  await build({
    root,
    mode,
    configFile: fileURLToPath(new URL('../vite.config.ts', import.meta.url)),
    logLevel: 'warn',
    build: { watch: watch ? {} : null },
  });
  console.log('  ✓ popup, options, background');

  // 2 ─ content scripts (IIFE; the public/ dir is already copied by step 1)
  for (const name of CONTENT_SCRIPTS) {
    await build({
      root,
      mode,
      configFile: false,
      publicDir: false,
      logLevel: 'warn',
      define,
      build: {
        outDir: `${dist}/content`,
        emptyOutDir: false,
        target: 'es2022',
        minify: mode !== 'development',
        sourcemap: false,
        watch: watch ? {} : null,
        lib: {
          entry: fileURLToPath(new URL(`../src/content/${name}.ts`, import.meta.url)),
          formats: ['iife'],
          name: `RabbitHole_${name}`,
          fileName: () => `${name}.js`,
        },
      },
    });
  }
  console.log(`  ✓ content scripts (${CONTENT_SCRIPTS.join(', ')})`);

  // 3 ─ manifest
  const manifest = createManifest({ backendUrl: env.VITE_BACKEND_URL, dev: mode === 'development' });
  await writeFile(`${dist}/manifest.json`, `${JSON.stringify(manifest, null, 2)}\n`);
  console.log('  ✓ manifest.json');

  console.log(
    watch
      ? '\nWatching for changes. Reload the extension at chrome://extensions after each rebuild.'
      : `\nDone → ${dist}\nLoad it via chrome://extensions → Developer mode → Load unpacked.`,
  );
}

main().catch((err) => {
  console.error('\n✗ Build failed\n', err);
  process.exit(1);
});
